### ISSUE TITLE
Marshal data too short

### ISSUE THREAD

**Issue by djberg96** [djberg96/pr-zlib#4]
Windows 8
ruby 2.2.2p95 (2015-04-13 revision 50295) [i386-mswin32_120]
Rubygems 2.4.6

I'm getting a "marshal data too short" on Windows 8 with a Visual Studio 13 build, after I did the "rake install_as_zlib" option. I tried deleting C:/Users/Daniel/.gem as per one solution I saw online for this particular error, but that had no effect.

```
C:\Users\Daniel>gem install ptools --backtrace --no-document
ERROR:  While executing gem ... (ArgumentError)
    marshal data too short
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/resolver/api_set.rb:117:in `load'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/resolver/api_set.rb:117:in `versions'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/resolver/api_set.rb:54:in `find_all'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/resolver/composed_set.rb:54:in `block in find_all'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/resolver/composed_set.rb:53:in `map'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/resolver/composed_set.rb:53:in `find_all'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/resolver/best_set.rb:30:in `find_all'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/resolver/installer_set.rb:151:in `find_all'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/resolver/installer_set.rb:54:in `add_always_install'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/dependency_installer.rb:463:in `resolve_dependencies'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/commands/install_command.rb:238:in `install_gem'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/commands/install_command.rb:299:in `block in install_gems'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/commands/install_command.rb:295:in `each'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/commands/install_command.rb:295:in `install_gems'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/commands/install_command.rb:202:in `execute'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/command.rb:307:in `invoke_with_build_args'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/command_manager.rb:168:in `process_args'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/command_manager.rb:138:in `run'
        C:/Ruby22VC/lib/ruby/2.2.0/rubygems/gem_runner.rb:54:in `run'
        C:/Ruby22VC/bin/gem.bat:28:in `<main>'
```

**Comment by phasis68** [comment]
I committed the patch.

**Comment by djberg96** [comment]
Thanks!
